from decimal import Decimal


def product(
    name: str,
    sku: str,
    category: str,
    price: str,
    stock_quantity: int,
    description: str,
    status: str = "active",
) -> dict:
    return {
        "name": name,
        "sku": sku,
        "category": category,
        "price": Decimal(price),
        "stock_quantity": stock_quantity,
        "status": status,
        "description": description,
    }


PRODUCTS = [
    product(
        "Wireless Keyboard",
        "KEY-001",
        "Electronics",
        "59.99",
        25,
        "Compact wireless keyboard",
    ),
    product(
        "Ergonomic Mouse",
        "MOU-001",
        "Electronics",
        "34.90",
        4,
        "Wireless ergonomic mouse",
    ),
    product(
        "USB-C Hub",
        "HUB-001",
        "Accessories",
        "49.90",
        2,
        "Seven-port USB-C hub",
    ),
    product(
        "Laptop Stand",
        "STA-001",
        "Office",
        "79.00",
        0,
        "Adjustable aluminium laptop stand",
        "inactive",
    ),
    product(
        "Webcam",
        "CAM-001",
        "Electronics",
        "64.50",
        8,
        "Full HD USB webcam",
    ),
    product(
        "Desk Lamp",
        "LAM-001",
        "Office",
        "45.00",
        5,
        "LED desk lamp",
    ),
    product(
        "Mechanical Keyboard",
        "KEY-002",
        "Electronics",
        "109.00",
        12,
        "Mechanical keyboard with tactile switches",
    ),
    product(
        "Noise-Cancelling Headphones",
        "HEA-001",
        "Audio",
        "149.00",
        3,
        "Wireless over-ear headphones",
    ),
    product(
        "Monitor Arm",
        "ARM-001",
        "Office",
        "84.00",
        7,
        "Adjustable monitor arm",
    ),
    product(
        "Portable SSD",
        "SSD-001",
        "Storage",
        "89.99",
        1,
        "One-terabyte portable SSD",
    ),
    product(
        "24-inch Monitor",
        "MON-001",
        "Displays",
        "179.00",
        14,
        "Full HD office monitor",
    ),
    product(
        "27-inch Monitor",
        "MON-002",
        "Displays",
        "269.00",
        9,
        "QHD productivity monitor",
    ),
    product(
        "Office Chair",
        "CHA-001",
        "Office",
        "229.00",
        6,
        "Ergonomic office chair",
    ),
    product(
        "Standing Desk",
        "DES-001",
        "Office",
        "499.00",
        11,
        "Electric height-adjustable desk",
    ),
    product(
        "Cable Organizer",
        "CAB-001",
        "Accessories",
        "14.90",
        30,
        "Desktop cable-management set",
    ),
    product(
        "USB Microphone",
        "MIC-001",
        "Audio",
        "89.00",
        10,
        "USB condenser microphone",
    ),
    product(
        "Desktop Speakers",
        "SPE-001",
        "Audio",
        "69.00",
        13,
        "Compact stereo speakers",
    ),
    product(
        "Desk Pad",
        "PAD-001",
        "Office",
        "24.90",
        20,
        "Large non-slip desk pad",
    ),
    product(
        "USB-C Dock",
        "DOC-001",
        "Accessories",
        "129.00",
        4,
        "Multi-display USB-C docking station",
    ),
    product(
        "Power Bank",
        "POW-001",
        "Electronics",
        "54.90",
        16,
        "Twenty-thousand mAh power bank",
    ),
    product(
        "Laptop Backpack",
        "BAC-001",
        "Bags",
        "74.00",
        18,
        "Water-resistant laptop backpack",
    ),
    product(
        "Laptop Sleeve",
        "CAS-001",
        "Bags",
        "29.90",
        22,
        "Protective 15-inch laptop sleeve",
    ),
    product(
        "Wireless Presenter",
        "WRI-001",
        "Accessories",
        "39.90",
        7,
        "Wireless presentation remote",
    ),
    product(
        "Notebook Set",
        "NOTE-001",
        "Stationery",
        "12.90",
        40,
        "Set of three notebooks",
    ),
    product(
        "Gel Pen Set",
        "PEN-001",
        "Stationery",
        "8.90",
        35,
        "Set of five gel pens",
    ),
    product(
        "Water Bottle",
        "BOT-001",
        "Office",
        "19.90",
        15,
        "Insulated stainless-steel bottle",
    ),
    product(
        "Anti-Fatigue Mat",
        "MAT-001",
        "Office",
        "59.00",
        3,
        "Standing-desk anti-fatigue mat",
    ),
    product(
        "Screen Cleaning Kit",
        "CLN-001",
        "Accessories",
        "11.90",
        28,
        "Screen cleaning spray and cloth",
    ),
    product(
        "Travel Adapter",
        "ADP-001",
        "Electronics",
        "32.00",
        5,
        "Universal travel power adapter",
    ),
    product(
        "Fast Charger",
        "CHR-001",
        "Electronics",
        "44.90",
        19,
        "Sixty-five-watt USB-C charger",
    ),
    product(
        "Drawing Tablet",
        "TAB-001",
        "Electronics",
        "119.00",
        6,
        "USB drawing tablet with stylus",
    ),
    product(
        "Wi-Fi Router",
        "ROU-001",
        "Networking",
        "139.00",
        8,
        "Dual-band Wi-Fi router",
    ),
    product(
        "Two-Bay NAS",
        "NAS-001",
        "Storage",
        "329.00",
        2,
        "Two-bay network storage device",
    ),
    product(
        "Label Printer",
        "PRI-001",
        "Office",
        "99.00",
        4,
        "Compact thermal label printer",
    ),
    product(
        "Label Roll Pack",
        "LAB-001",
        "Office",
        "18.90",
        25,
        "Pack of three thermal label rolls",
    ),
]

ORDER_SPECS = [
    (
        "ORD-1001",
        "Anna Schmidt",
        "anna@example.com",
        "delivered",
        35,
        [("KEY-001", 1), ("MOU-001", 1)],
    ),
    (
        "ORD-1002",
        "David Fischer",
        "david@example.com",
        "pending",
        32,
        [("HUB-001", 2)],
    ),
    (
        "ORD-1003",
        "Sophie Weber",
        "sophie@example.com",
        "processing",
        30,
        [("STA-001", 1), ("LAM-001", 1)],
    ),
    (
        "ORD-1004",
        "Leon Wagner",
        "leon@example.com",
        "shipped",
        28,
        [("KEY-002", 1), ("SSD-001", 1)],
    ),
    (
        "ORD-1005",
        "Laura Becker",
        "laura@example.com",
        "delivered",
        26,
        [("CAM-001", 2)],
    ),
    (
        "ORD-1006",
        "Jonas Hoffmann",
        "jonas@example.com",
        "cancelled",
        25,
        [("HEA-001", 1)],
    ),
    (
        "ORD-1007",
        "Mia Schulz",
        "mia@example.com",
        "delivered",
        23,
        [("ARM-001", 2)],
    ),
    (
        "ORD-1008",
        "Noah Braun",
        "noah@example.com",
        "pending",
        22,
        [("MOU-001", 1), ("HUB-001", 1)],
    ),
    (
        "ORD-1009",
        "Emma Keller",
        "emma@example.com",
        "processing",
        20,
        [("MON-001", 1), ("CAB-001", 2)],
    ),
    (
        "ORD-1010",
        "Paul Richter",
        "paul@example.com",
        "delivered",
        19,
        [("CHA-001", 1)],
    ),
    (
        "ORD-1011",
        "Lena Wolf",
        "lena@example.com",
        "shipped",
        18,
        [("DOC-001", 1), ("CHR-001", 1)],
    ),
    (
        "ORD-1012",
        "Felix Neumann",
        "felix@example.com",
        "pending",
        17,
        [("BAC-001", 1), ("CAS-001", 1)],
    ),
    (
        "ORD-1013",
        "Clara Hartmann",
        "clara@example.com",
        "delivered",
        16,
        [("SPE-001", 1), ("MIC-001", 1)],
    ),
    (
        "ORD-1014",
        "Elias Krueger",
        "elias@example.com",
        "cancelled",
        15,
        [("DES-001", 1)],
    ),
    (
        "ORD-1015",
        "Marie Vogel",
        "marie@example.com",
        "processing",
        14,
        [("POW-001", 2), ("ADP-001", 1)],
    ),
    (
        "ORD-1016",
        "Luca Frank",
        "luca@example.com",
        "delivered",
        13,
        [("PAD-001", 1), ("NOTE-001", 2), ("PEN-001", 1)],
    ),
    (
        "ORD-1017",
        "Hannah Berger",
        "hannah@example.com",
        "shipped",
        12,
        [("TAB-001", 1)],
    ),
    (
        "ORD-1018",
        "Finn Roth",
        "finn@example.com",
        "pending",
        11,
        [("BOT-001", 2), ("CLN-001", 1)],
    ),
    (
        "ORD-1019",
        "Julia Werner",
        "julia@example.com",
        "delivered",
        10,
        [("MON-002", 1), ("ARM-001", 1)],
    ),
    (
        "ORD-1020",
        "Max Schmitt",
        "max@example.com",
        "processing",
        9,
        [("ROU-001", 1), ("CHR-001", 2)],
    ),
    (
        "ORD-1021",
        "Lea Schuster",
        "lea@example.com",
        "delivered",
        8,
        [("NAS-001", 1), ("SSD-001", 2)],
    ),
    (
        "ORD-1022",
        "Ben Kaiser",
        "ben@example.com",
        "pending",
        7,
        [("PRI-001", 1), ("LAB-001", 3)],
    ),
    (
        "ORD-1023",
        "Sarah Lorenz",
        "sarah@example.com",
        "shipped",
        6,
        [("WRI-001", 1), ("NOTE-001", 1)],
    ),
    (
        "ORD-1024",
        "Tim Boehm",
        "tim@example.com",
        "cancelled",
        5,
        [("MAT-001", 1)],
    ),
    (
        "ORD-1025",
        "Nina Sommer",
        "nina@example.com",
        "delivered",
        4,
        [("KEY-002", 1), ("HEA-001", 1), ("PAD-001", 1)],
    ),
    (
        "ORD-1026",
        "Jan Peters",
        "jan@example.com",
        "processing",
        3,
        [("CAM-001", 1), ("MIC-001", 1)],
    ),
    (
        "ORD-1027",
        "Lisa Brandt",
        "lisa@example.com",
        "pending",
        2,
        [("DES-001", 1), ("MAT-001", 1)],
    ),
    (
        "ORD-1028",
        "Tom Seidel",
        "tom@example.com",
        "delivered",
        1,
        [("DOC-001", 1), ("MON-002", 1), ("CHA-001", 1)],
    ),
]
